sudo: false  # Use container-based infrastructure
language: python
python:
  - "3.8"
  - "3.10"
os:
  - linux
  - windows
  - osx
cache:
  pip: true
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  # reset the shell's lookup table for program name to path mappings
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - python --version
install:
  - >
      conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
      nose numpy scipy pandas mkl tensorflow pip cython
  - source activate test-environment
  # install pysam from conda because I'm having trouble installing Cython
  # for Python 3 on Travis
  - conda install -c bioconda pysam
  - pip install -r requirements.txt --ignore-installed
  - pip install .
  - pip install coveralls
before_script:
  - ./lint.sh
script:
  - nosetests test --with-coverage --cover-package=weirdo
after_success:
  coveralls
